name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Linting & vetting.
        env:
          GOBIN: /tmp/.bin
        run: make lint
  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18.x", "1.19.x"]
        platform: [ubuntu-latest, macos-latest]

    name: Unit tests on Go ${{ matrix.go }} ${{ matrix.platform }}
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install docker - MacOS
        if: runner.os == 'macOS'
        run: |
          brew install docker colima kind kubectl
          # Ensure Lima guest is accessible from mac host.
          colima start --network-address
          # Find the IP address of the Lima guest.
          IP=$(limactl shell colima -- ip a show dev col0 | head -n3 | tail -n1 | cut -d' ' -f6 | rev | cut -c4- | rev)
          # Route packets destined for 172/8 through the Lima guest.
          sudo route -nv add -net 172 $IP
          # Configure the Lima guest to forward packets from the col0 bridge to Docker containers.
          limactl shell colima -- sudo iptables -t filter -A FORWARD -s $IP/24 -d 172.0.0.0/8 -j ACCEPT

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run unit tests.
        env:
          GOBIN: /tmp/.bin
        run: make test
